name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main  # Runs on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Ensures a Linux-based environment

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure this matches your Azure Web App runtime

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: "azure-ml-example-api"
        slot-name: "production"
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
